---
kind: pipeline
name: windows-1809
platform:
  os: windows
  arch: amd64
  version: 1809
steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.5.6
    commands:
      - "docker build -f Dockerfile.windows --build-arg WINDOWS_VERSION=1809 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - "WINDOWS_VERSION=1809"
        - "ARCH=amd64"
        - "VERSION=${DRONE_TAG}"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile.windows
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "rancher/fluent-bit"
      tag: "${DRONE_TAG}-windows-1809"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: windows-1903
platform:
  os: windows
  arch: amd64
  version: 1903
steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.5.6
    commands:
      - "docker build -f Dockerfile.windows --build-arg WINDOWS_VERSION=1903 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - "WINDOWS_VERSION=1903"
        - "ARCH=amd64"
        - "VERSION=${DRONE_TAG}"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile.windows
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "rancher/fluent-bit"
      tag: "${DRONE_TAG}-windows-1903"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: windows-1909
platform:
  os: windows
  arch: amd64
  version: 1909
steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.5.6
    commands:
      - "docker build -f Dockerfile.windows --build-arg WINDOWS_VERSION=1909 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - "WINDOWS_VERSION=1909"
        - "ARCH=amd64"
        - "VERSION=${DRONE_TAG}"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile.windows
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "rancher/fluent-bit"
      tag: "${DRONE_TAG}-windows-1909"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: windows-2004
platform:
  os: windows
  arch: amd64
  version: 2004
# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true
steps:
  - name: clone
    image: luthermonson/drone-git:windows-2004-amd64
  - name: build
    pull: always
    image: rancher/dapper:v0.5.6
    commands:
      - "docker build -f Dockerfile.windows --build-arg WINDOWS_VERSION=2004 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
  - name: docker-publish
    image: luthermonson/drone-docker:2004
    settings:
      build_args:
        - "WINDOWS_VERSION=2004"
        - "ARCH=amd64"
        - "VERSION=${DRONE_TAG}"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile.windows
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "rancher/fluent-bit"
      tag: "${DRONE_TAG}-windows-2004"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: windows-20H2
platform:
  os: windows
  arch: amd64
  version: 20H2
# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true
steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
  - name: build
    pull: always
    image: rancher/dapper:v0.5.6
    commands:
      - "docker build -f Dockerfile.windows --build-arg WINDOWS_VERSION=20H2 ."
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag
  - name: docker-publish
    image: luthermonson/drone-docker:20H2
    settings:
      build_args:
        - "WINDOWS_VERSION=20H2"
        - "ARCH=amd64"
        - "VERSION=${DRONE_TAG}"
      custom_dns: 1.1.1.1
      dockerfile: Dockerfile.windows
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "rancher/fluent-bit"
      tag: "${DRONE_TAG}-windows-20H2"
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/master
        - refs/tags/*
volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: linux-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    image: rancher/dapper:v0.5.6
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - "export FLUENTBIT_VERSION=1.6.10"
      - "docker pull fluent/fluent-bit:x86_64-$FLUENTBIT_VERSION"
      - "docker tag fluent/fluent-bit:x86_64-$FLUENTBIT_VERSION rancher/fluent-bit:${DRONE_TAG}-linux-amd64"
      - "echo $PASSWORD | docker login --password-stdin --username $USERNAME"
      - "docker push rancher/fluent-bit:${DRONE_TAG}-linux-amd64"
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: linux-arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: build
    image: rancher/dapper:v0.5.6
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - "export FLUENTBIT_VERSION=1.6.10"
      - "docker pull fluent/fluent-bit:arm64v8-$FLUENTBIT_VERSION"
      - "docker tag fluent/fluent-bit:arm64v8-$FLUENTBIT_VERSION rancher/fluent-bit:${DRONE_TAG}-linux-arm64"
      - "echo $PASSWORD | docker login --password-stdin --username $USERNAME"
      - "docker push rancher/fluent-bit:${DRONE_TAG}-linux-arm64"
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: linux-arm
platform:
  os: linux
  arch: arm
steps:
  - name: build
    image: rancher/dapper:v0.5.6
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - "export FLUENTBIT_VERSION=1.6.10"
      - "docker pull fluent/fluent-bit:arm32v7-$FLUENTBIT_VERSION"
      - "docker tag fluent/fluent-bit:arm32v7-$FLUENTBIT_VERSION rancher/fluent-bit:${DRONE_TAG}-linux-arm"
      - "echo $PASSWORD | docker login --password-stdin --username $USERNAME"
      - "docker push rancher/fluent-bit:${DRONE_TAG}-linux-arm"
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: manifest
platform:
  os: linux
  arch: amd64
steps:
  - name: push-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      spec: manifest.tmpl
    when:
      instance:
        include:
          - drone-publish.rancher.io
      event:
        - tag
trigger:
    event:
      exclude:
        - promote
depends_on:
  - windows-1809
  - windows-1903
  - windows-1909
  - windows-2004
  - windows-20H2
  - linux-amd64
  - linux-arm64
  - linux-arm
